# .github/release-drafter.yml
---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
  - title: '🧨 Breaking Changes'
    labels:
      - 'break'
  - title: '🎨 Styling'
    labels:
      - 'style'
  - title: 'CI/CD Updates'
    labels:
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'break'
  minor:
    labels:
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'style'
  default: patch
autolabeler:
  - label: 'feat'
    title:
      - '^feat:'
  - label: 'fix'
    title:
      - '^fix:'
  - label: 'break'
    title:
      - '^break:'
  - label: 'style'
    title:
      - '^style:'
template: |
  ## Changes

  $CHANGES

  ----------------------------------------------

  ## Contributors
  
  $CONTRIBUTORS
