name: Release Drafter

on:
  push:
    branches:
      - "v.*"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write        # needed to create releases
      pull-requests: write   # needed for autolabeler
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}